title: "Codera"
email: battaroberto@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Roberto
paginate: 30
#disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  robertobatts:
    name: Roberto
    display_name: Roberto
    avatar: 'assets/images/roberto.png'
    email: battaroberto@gmail.com
    web: https://www.robertobattaglia.com/
    twitter: https://twitter.com/wowthemesnet
    description: "Founder and Author of Codera, a website for all the people who want to improve their coding skills."

# Social
#social:
#  instagram: https://www.instagram.com/bootstrapstarter/
#  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
#  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives